version: '3.8'

services:
  postgres-prod:
    image: postgres:16-alpine
    container_name: pramukhraj_db_prod
    restart: always
    env_file: 
      - ../.env.prod # Steps out of DB_Folder into Docker_Folder
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: ${DB_TIMEZONE}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg-prod-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prod-network
      
volumes:
  pg-prod-data:
    name: pramukhraj_pg_prod_data

networks:
  prod-network:
    driver: bridge